version: '3.9'
services:
  api:
    build: ./server
    environment:
      PORT: 4000
      DATABASE_URL: postgres://postgres:postgres@db:5432/vetholim
      REDIS_URL: redis://redis:6379
      APP_ENV: development
      SERVICE_NAME: vetholim-api
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      LOAD_TEST_TOKEN: dev-loadtest
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis
    command: ["node", "dist/index.js"]

  client:
    build: ./client
    ports:
      - "8080:80"
    depends_on:
      - api

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vetholim
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  otel-collector:
    image: otel/opentelemetry-collector:0.102.1
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./deploy/otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4318:4318"
