apiVersion: v1
kind: Service
metadata:
  name: vetholim-api
  namespace: vetholim
  labels:
    app: vetholim
    tier: backend
spec:
  selector:
    app: vetholim
    tier: backend
  ports:
    - name: http
      port: 80
      targetPort: 4000
  type: ClusterIP
